# Generated by Django 5.0.4 on 2024-07-08 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "1. Dr Department",
                "verbose_name_plural": "1. Dr Departments",
            },
        ),
        migrations.CreateModel(
            name="DoctorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("mobile_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=200)),
                ("age", models.CharField(max_length=3)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctordepartments.drdepartment",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. Doctor Details",
                "verbose_name_plural": "2. Doctor Details",
            },
        ),
    ]
