# Generated by Django 5.0.4 on 2024-07-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctordepartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetails",
            name="doctor_id",
            field=models.CharField(
                blank=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
